### ISSUE TITLE
执行时间判断上是否存在问题，这个很疑惑。

### ISSUE THREAD

**Issue by pixelvm** [iwannay/jiacrontab#104]
日志上查看存在大量执行失败的定时任务。
下面是部分日志的截图。
排查了列表所有定时任务，发现也存在成功执行的。
![image](https://user-images.githubusercontent.com/888163/112244036-94376a80-8c89-11eb-8f3a-4f26f3085b10.png)

**Comment by iwannay** [comment]
在旧的版本中执行之前会校验时间，如果数据库阻塞较长可能出现因时间校验失败而产生的执行失败

**Comment by hankerdream** [comment]
新版本是否已经解决了该问题？

**Comment by iwannay** [comment]
@hankerdream 已经修复，直接替换二进制命令即可
