### ISSUE TITLE
Windows平台执行python文件输出log显示为乱码

### ISSUE THREAD

**Issue by lincanyi** [iwannay/jiacrontab#113]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46511674/127311396-88188eee-7e15-48d2-a447-11f54d1d258f.png)
![image](https://user-images.githubusercontent.com/46511674/127311517-9b89e45a-a799-4d3d-8201-74865fea29b3.png)

**Comment by lincanyi** [comment]
![image](https://user-images.githubusercontent.com/46511674/127311674-228fcc29-47c7-45da-8802-86e66f1762b5.png)

**Comment by lincanyi** [comment]
大佬帮忙看看

**Comment by iwannay** [comment]
需要脚本设置utf8，jiacrontab 默认为utf8编码
