### ISSUE TITLE
可以支持http接口投递任务吗 这样可以在其他系统投递任务了

### ISSUE THREAD

**Issue by ZGINMADAO** [iwannay/jiacrontab#115]

**Comment by iwannay** [comment]
什么意思？

**Comment by wxy545812093** [comment]
> 什么意思？

他意思是：想在第三方系统里直接调用jiacrontab系统的任务维护API（如 curl  -d "xxxx" https://xx.com/task/create），以达到不用进jiacrontab 管理后台就能发布任务。

**Comment by iwannay** [comment]
> > 什么意思？
> 
> 他意思是：想在第三方系统里直接调用jiacrontab系统的任务维护API（如 curl -d "xxxx" [https://xx.com/task/create），以达到不用进jiacrontab](https://xx.com/task/create%EF%BC%89%EF%BC%8C%E4%BB%A5%E8%BE%BE%E5%88%B0%E4%B8%8D%E7%94%A8%E8%BF%9Bjiacrontab) 管理后台就能发布任务。

可以直接通过http调用接口创建任务的
