### ISSUE TITLE
实用需求提交

### ISSUE THREAD

**Issue by wolfboy55** [iwannay/jiacrontab#21]
新增任务中断，可供用户选择，失败重跑次数选项：次数 0和1选项；

jobx与Saturn，xxl-job 等分布式任务调度平台都有这个功能，比较实用，所以建议作者加上；
![5](https://user-images.githubusercontent.com/33387758/46189271-55c2ce00-c320-11e8-91ab-8282d4305590.png)

**Comment by iwannay** [comment]
会在未来考虑的
