### ISSUE TITLE
定时任务中一些特殊字符无法使用

### ISSUE THREAD

**Issue by mzky** [iwannay/jiacrontab#25]
比如 echo `date +%Y%m%d` >>/opt/1

![_20181112141850](https://user-images.githubusercontent.com/13345233/48330023-178e2d80-e686-11e8-942c-5062b0e2596e.png)

![_20181112141633](https://user-images.githubusercontent.com/13345233/48329912-af3f4c00-e685-11e8-9527-bd07b57f9972.png)

![_20181112141747](https://user-images.githubusercontent.com/13345233/48329941-ce3dde00-e685-11e8-8fee-fd5ac2eb0ee8.png)

其中`符号和>>都不能使用

改进建议：
1. go代码exec.Command("/bin/bash", "-c", "echo  echo `date +%Y%m%d` >>/opt/1").Run()
2. 建议增加一些全局变量，比如自定义重定向文件、获取当前时间等

**Comment by iwannay** [comment]
@mzky多谢建议
 第一条的话下个版本会考虑改进。
 第二条的话因为并没有其他用户有此类需求，所以暂不在计划之列，不过欢迎提交经过测试的pr。
