### ISSUE TITLE
是否考虑增加，秒级计划任务，否则和系统cron 区别不大

### ISSUE THREAD

**Issue by ferocknew** [iwannay/jiacrontab#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ferocknew** [comment]
fork 了你的作品，做了修改，能支持秒级跑批，不知道怎么推送给你。

commit 地址：https://github.com/ferocknew/jiacrontab/commit/4d5bf2c7c55116d59ecbdf024d408871c51034d8

**Comment by wolfboy55** [comment]
可以更新，合并master分支，提供给用户下载，更新版本就可以了

**Comment by ferocknew** [comment]
已提 pull request

**Comment by iwannay** [comment]
新版修改了实现方式，新版现在已经支持秒了。
