### ISSUE TITLE
运行列表中增加一列备注

### ISSUE THREAD

**Issue by wolfboy55** [iwannay/jiacrontab#32]
![6](https://user-images.githubusercontent.com/33387758/50389118-ab144d00-0760-11e9-9b24-8714efc04193.png)

期望再ip列表里，新增一列备注，或者自动生成主机hosts，方便区别机器，因为阿里云专有网络，ip内网地址很接近，用户体验度降低

**Comment by iwannay** [comment]
2.0版已添加
