### ISSUE TITLE
api报警能否以变量的形式获取主机IP和脚本名称

### ISSUE THREAD

**Issue by loveyang2012** [iwannay/jiacrontab#36]
**api报警能否以变量的形式获取主机IP和脚本名称**
在调用api报警时能否以变量的形式获取报警主机ip和脚本名称
比如以下api
http://12.16.13.11:88?touser=YangShengLin&subject=crontab&message=172.16.136.142+test

message为报警内容：IP地址和脚本名称能否以变量的形式获取当前主机和脚本名称

**Comment by iwannay** [comment]
现在消息体中已包含报警主机地址
