### ISSUE TITLE
一点建议 和bug

### ISSUE THREAD

**Issue by station19** [iwannay/jiacrontab#4]
首先非常感谢作者的辛勤付出，以下个人愚见，希望有时间瞅瞅

### 建议 ###
① 希望能展示 脚本执行的次数
② server配置邮件时，希望增加协议自定义（如SSL/TLS），企业邮箱基本都是加密服务，而且阿里云25端口忒麻烦
③增加 已添加的 crontab配置的导入导出备份/恢复
④批量模式下，可以按 状态排序，如果计划任务比较多，状态 开启和关闭的就会显示的比较乱
⑤界面增加任务执行成功或者失败的标示
⑥日志写在文件里终究不太好，建议使用mongodb

### bug ###
① 添加新任务时选择取消 ，无任何反应，取消按钮不生效
② 貌似脚本不支持管道啊（如 ps -ef|grep nginx） 之类的，server.ini设置command 支持ps后也不行

### 疑惑 ###
① 已编译的包貌似在macos下无法运行,提示 ./server: ./server: cannot execute binary file

**Comment by iwannay** [comment]
关于提供的建议：
1、脚本执行次数会在下个版本添加。
2、关于邮件的建议也会采纳。
3、可以增加导出备份功能，后期会考虑支持linux crontab导入。
4、排序也会有的。
5、界面可以添加上次任务执行状态。
6、日志这个我想下，因为暂时没引入数据库。

关于bug：
1、取消按钮其实是个reload操作，我这里暂时没有重现，后面我多试试。
2、对的管道暂时不支持，不过可能会在未来支持（这是个比较实用的功能）

关于疑惑：
需要linux-amd64平台，，mac平台可手动编译后执行
感谢支持
