### ISSUE TITLE
架构过于简单了，初步看来，是没有存储或依赖文件存储的

### ISSUE THREAD

**Issue by xkeyideal** [iwannay/jiacrontab#6]
原生的rpc太原生了。
没看到存储结构，历史操作记录如何存储的？
如果rpc通信失败怎么办，client是否直接脱离server的控制了？

感觉思路应该不错，实现过于草率，生产环境慎用。

初步看源码的结论，希望作者能整理出架构图和说明文档

**Comment by iwannay** [comment]
rpc 通信失败 server会收到反馈的。
该项目目前持久化存储为自身提供的文件存储。
该项目目前的原则是追求简单可用。。
定位是对于正在使用linux自身crontab的用户，提供一个简单的替换方案。
如果是对于大型项目或高级用户。。建议慎重使用。
