### ISSUE TITLE
一些linux常用命令不支持吗？

### ISSUE THREAD

**Issue by johnnyzhouzhou** [iwannay/jiacrontab#61]
运行这个也会报错 sudo ps -ef|grep python |grep -E 'timing_sync_setting_files.py' |awk '{print "kill -9 "$2}' |sh

error: unsupported SysV option

Usage:

ps [options]

Try 'ps --help <simple|list|output|threads|misc|all>'

or 'ps --help <s|l|o|t|m|a>'

for additional help text.

For more details see ps(1).

[192.168.15.103:20003 kill timing_sync_setting_files.py] exit status 1

**Comment by iwannay** [comment]
@johnnyzhouzhou  如果非root用户执行sudo需要输入密码
管道命令需要在code中编辑，例如：sh -c  ps -ef|grep python |grep -E 'timing_sync_setting_files.py' |awk '{print "kill -9 "$2}' |sh
