### ISSUE TITLE
建议增加一个功能

### ISSUE THREAD

**Issue by marchhappy** [iwannay/jiacrontab#7]
在crontab中，类似于cd /data/home/CheckServerAlive && python dial.py  这样的脚本命令，是无法在jiacrontab进行配置的。可否添加该功能的支持？

**Comment by iwannay** [comment]
谢谢反馈。。这个功能其实在添加pipe调用的时候，有考虑添加的。
但考虑到该命令可以通过shell脚本实现暂未添加。 
不过下个版本 会重新考量加入的
