### ISSUE TITLE
新建节点分组并将节点移动时候报错

### ISSUE THREAD

**Issue by lizeyun** [iwannay/jiacrontab#72]
![image](https://user-images.githubusercontent.com/19726385/77377681-cda37480-6dae-11ea-8fb8-a13504a8844f.png)

看样子像是唯一索引

**Comment by lizeyun** [comment]
在分组-用户列表中 ， 新建分组，直接退出登录态，再登录数据全没了。。你这个bug有点严重呀~

喜欢你这个UI

**Comment by iwannay** [comment]
@lizeyun 什么数据没了？

**Comment by lizeyun** [comment]
![image](https://user-images.githubusercontent.com/19726385/77396473-d01dc280-6dde-11ea-9cfb-2f8f1653d59f.png)
![image](https://user-images.githubusercontent.com/19726385/77396489-d3b14980-6dde-11ea-9781-1456906140fc.png)
按照图1点击确定，就报图2的错，然后再登录，就看不到节点了。。我的节点全部消失了，

**Comment by lizeyun** [comment]
好像是因为，我再次登录就不是管理员用户呢？？ 因为我在导航栏也看不到分组了，

**Comment by iwannay** [comment]
你两次是同一个账号登录的么？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lizeyun"<notifications@github.com&gt;; 
发送时间: 2020年3月24日(星期二) 下午2:53
收件人: "iwannay/jiacrontab"<jiacrontab@noreply.github.com&gt;; 
抄送: "772648576"<772648576@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [iwannay/jiacrontab] 新建节点分组并将节点移动时候报错 (#72)





 
好像是因为，我再次登录就不是管理员用户呢？？ 因为我在导航栏也看不到分组了，

**Comment by lizeyun** [comment]
> 你两次是同一个账号登录的么？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lizeyun"<notifications@github.com&gt;; 发送时间: 2020年3月24日(星期二) 下午2:53 收件人: "iwannay/jiacrontab"<jiacrontab@noreply.github.com&gt;; 抄送: "772648576"<772648576@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [iwannay/jiacrontab] 新建节点分组并将节点移动时候报错 (#72) 好像是因为，我再次登录就不是管理员用户呢？？ 因为我在导航栏也看不到分组了， — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

确定啊，都是admin， 只有这一个账号

**Comment by iwannay** [comment]
那是因为，这个功能是修改当前用户的分组，你把自己的分组改了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lizeyun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午2:53
收件人:&nbsp;"iwannay/jiacrontab"<jiacrontab@noreply.github.com&gt;;
抄送:&nbsp;"772648576"<772648576@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [iwannay/jiacrontab] 新建节点分组并将节点移动时候报错 (#72)





 
好像是因为，我再次登录就不是管理员用户呢？？ 因为我在导航栏也看不到分组了，

**Comment by lizeyun** [comment]
那我还能恢复吗 - - 尴尬

**Comment by iwannay** [comment]
可以，你直接修改数据库里面的分组就好了。

**Comment by lizeyun** [comment]
好的，谢谢，功能很棒~
