### ISSUE TITLE
任务描述

### ISSUE THREAD

**Issue by crhstack** [iwannay/jiacrontab#75]
由于定时任务比较多，不容易区分，建议
可以增加一个任务的描述

**Comment by iwannay** [comment]
@crhstack 任务名不是可以区分么？

**Comment by crhstack** [comment]
@iwannay  你说的任务名是脚本名称吗？
当一个脚本有多个任务，通过传参的形式执行不同任务的时候，就不太好区分了

**Comment by iwannay** [comment]
@crhstack 脚本名-任务名，，这样的命名格式是否可以解决一个脚本有多个任务的场景？

**Comment by crhstack** [comment]
@iwannay 抱歉 我理解的有点问题
编辑任务中，脚本名称就可以写成任务名称，在执行命令中才是指定真实的脚本名称，
这样是可以区分的。
感谢
