### ISSUE TITLE
服务器挂掉重启服务，进程数一直为1

### ISSUE THREAD

**Issue by neroanelli** [iwannay/jiacrontab#84]
**Describe the bug**
 - 1 在运行过程中，如果服务器异常挂掉，重启`jiacrontab`服务，原有的任务进程数没有清零，导致进程数限制为1的任务无法启动，也无法手动执行，提示超过最大并发数。
 - 2 编辑**正在执行**中的任务，点击保存后。正在执行的任务不会被杀掉，还是会继续执行。而且这个进程脱离了`jiacrontab`的控制，没有办法强杀，也没办法手动执行（假如进程数限制为1，会提示超过并发数）

**Comment by nballen-tx** [comment]
出现同样的问题，新版有修复吗？谢谢

**Comment by neroanelli** [comment]
是的，这个问题很容易复现。我测试过多次：在系统正常运行过程中，强制结束掉`jiacrontab`的进程，重新启动`jiacrontab`之后，所有任务的进程数没有清零。
出现这种情况之后，我只能手动打开数据库，然后将表中的`processNum`字段全部清零，然后重新启动`jiacrontab`服务，恢复正常。

**Comment by iwannay** [comment]
该bug会在下个版本（近期）修复
