### ISSUE TITLE
常驻任务不会自动创建日志文件

### ISSUE THREAD

**Issue by shenyuanheli** [iwannay/jiacrontab#87]
1.目前可以确定任务不管执行成功失败都会有输出，是常驻任务 会一直执行的。
2.每天的第一次打开会提示没有日志文件
3.然后把任务停掉再打开这个时候就不会提示日志文件不存在了，也能看到日志。
![image](https://user-images.githubusercontent.com/70498139/91678214-8a2c0e00-eb77-11ea-8394-7ddec6c58436.png)
4.希望作者看到修复一下。。。。

**Comment by iwannay** [comment]
@shenyuanheli 已加入修复列表

**Comment by iwannay** [comment]
已修复
