### ISSUE TITLE
【需求申请】支持多触发器功能

### ISSUE THREAD

**Issue by CharlesTea** [iwannay/jiacrontab#91]
一个定时任务能否支持多个触发器，这个需求应该还挺普遍的，一个触发器的表达能力还是有限。

**Comment by iwannay** [comment]
@CharlesTea 多个触发器具体指什么？

**Comment by CharlesTea** [comment]
> @CharlesTea 多个触发器具体指什么？
_定时任务格式：
    Second Minute Hour Day Month Week
    秒 分钟 小时 天 月 星期
    0-59 0-59 0-23 1-31 1-12 0-6_
只要有一个满足条件就生成任务，比如我想8-9点之间每10分钟跑一次，18-19点每半个小时跑一次可以配置两条：
0 */10 8-9 * *
0 */30 18-19 * * 

有的时候逻辑比较复杂，一个触发器不够。

**Comment by CharlesTea** [comment]
> @CharlesTea 多个触发器具体指什么？
