### ISSUE TITLE
常驻任务日志倒序查询时无数据返回

### ISSUE THREAD

**Issue by lgs3137** [iwannay/jiacrontab#92]
常驻任务日志倒序查询时无数据返回，这个是针对日志格式有要求的么？

**Comment by lgs3137** [comment]
![image](https://user-images.githubusercontent.com/1278141/97854018-db9d7880-1d33-11eb-933f-92acb0baea23.png)

![image](https://user-images.githubusercontent.com/1278141/97853957-c9bbd580-1d33-11eb-924f-d0d0f28eda3a.png)

**Comment by lgs3137** [comment]
另外，发现常驻任务跨日后没有自动生成新日期的日志文件。。。

**Comment by iwannay** [comment]
@lgs3137 已加入修复列表

**Comment by iwannay** [comment]
已修复
